[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_CONFIG_OPTIONAL = "false"
  NPM_FLAGS = "--legacy-peer-deps"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

