[build]
  command = "npm run build"
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"


[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_CONFIG_OPTIONAL = "true"
  NPM_FLAGS = "--legacy-peer-deps"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

