[build]
  command = "npm run build"
  publish = "dist"  # or "dist" depending on your framework




[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

    [build.environment]
  NODE_VERSION = "18"
  VITE_SSR_NO_EXTERNAL = "true"
